#!/bin/bash
for i in `ls ../images/about`; do /usr/local/Cellar/imagemagick/7.0.7-1/bin/convert ../images/about/"$i" -sampling-factor 4:2:0 -resize 780x650 -strip -quality 85 -interlace JPEG -colorspace RGB about/"$i"; done
for i in `ls ../images/artist-bio`; do /usr/local/Cellar/imagemagick/7.0.7-1/bin/convert ../images/artist-bio/"$i" -sampling-factor 4:2:0 -resize 780x650 -strip -quality 85 -interlace JPEG -colorspace RGB artist-bio/"$i"; done
for i in `ls ../images/les-lumieres`; do /usr/local/Cellar/imagemagick/7.0.7-1/bin/convert ../images/les-lumieres/"$i" -sampling-factor 4:2:0 -resize 780x650 -strip -quality 85 -interlace JPEG -colorspace RGB les-lumieres/"$i"; done
for i in `ls ../images/the-plate-throwers`; do /usr/local/Cellar/imagemagick/7.0.7-1/bin/convert ../images/the-plate-throwers/"$i" -sampling-factor 4:2:0 -resize 780x650 -strip -quality 85 -interlace JPEG -colorspace RGB the-plate-throwers/"$i"; done
for i in `ls ../images/oceans-of-notions`; do /usr/local/Cellar/imagemagick/7.0.7-1/bin/convert ../images/oceans-of-notions/"$i" -sampling-factor 4:2:0 -resize 780x650 -strip -quality 85 -interlace JPEG -colorspace RGB oceans-of-notions/"$i"; done
for i in `ls ../images/parchemins`; do /usr/local/Cellar/imagemagick/7.0.7-1/bin/convert ../images/parchemins/"$i" -sampling-factor 4:2:0 -resize 780x650 -strip -quality 85 -interlace JPEG -colorspace RGB parchemins/"$i"; done
for i in `ls ../images/return-to-form`; do /usr/local/Cellar/imagemagick/7.0.7-1/bin/convert ../images/return-to-form/"$i" -sampling-factor 4:2:0 -resize 780x650 -strip -quality 85 -interlace JPEG -colorspace RGB return-to-form/"$i"; done
for i in `ls ../images/surface-details`; do /usr/local/Cellar/imagemagick/7.0.7-1/bin/convert ../images/surface-details/"$i" -sampling-factor 4:2:0 -resize 780x650 -strip -quality 85 -interlace JPEG -colorspace RGB surface-details/"$i"; done
